// Generated by Wrangler by running `wrangler types`

interface Env {
  PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_live_51Q9XhzK7kf3vNCJg3Sh2dUmBpMKsFLP3PSYIiUgqfRX8SlYIuYUWXRTXd7MFEXRdYd0ct177FTZQZj82r7jRm0ev00jhuEF4VE";
}
